//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Udemy.WebServisOrnekUygulamaConsole.UrunWebServis {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UrunServisSoap", Namespace="http://tempuri.org/")]
    public partial class UrunServis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Guvenlik guvenlikValueField;
        
        private System.Threading.SendOrPostCallback UrunKayitDuzenleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UrunKayitSilOperationCompleted;
        
        private System.Threading.SendOrPostCallback UrunTumListeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UrunGetirOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UrunServis() {
            this.Url = global::Udemy.WebServisOrnekUygulamaConsole.Properties.Settings.Default.Udemy_WebServisOrnekUygulamaConsole_UrunWebServis_UrunServis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Guvenlik GuvenlikValue {
            get {
                return this.guvenlikValueField;
            }
            set {
                this.guvenlikValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UrunKayitDuzenleCompletedEventHandler UrunKayitDuzenleCompleted;
        
        /// <remarks/>
        public event UrunKayitSilCompletedEventHandler UrunKayitSilCompleted;
        
        /// <remarks/>
        public event UrunTumListeCompletedEventHandler UrunTumListeCompleted;
        
        /// <remarks/>
        public event UrunGetirCompletedEventHandler UrunGetirCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GuvenlikValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UrunKayitDuzenle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutputType UrunKayitDuzenle(Urun U) {
            object[] results = this.Invoke("UrunKayitDuzenle", new object[] {
                        U});
            return ((OutputType)(results[0]));
        }
        
        /// <remarks/>
        public void UrunKayitDuzenleAsync(Urun U) {
            this.UrunKayitDuzenleAsync(U, null);
        }
        
        /// <remarks/>
        public void UrunKayitDuzenleAsync(Urun U, object userState) {
            if ((this.UrunKayitDuzenleOperationCompleted == null)) {
                this.UrunKayitDuzenleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUrunKayitDuzenleOperationCompleted);
            }
            this.InvokeAsync("UrunKayitDuzenle", new object[] {
                        U}, this.UrunKayitDuzenleOperationCompleted, userState);
        }
        
        private void OnUrunKayitDuzenleOperationCompleted(object arg) {
            if ((this.UrunKayitDuzenleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UrunKayitDuzenleCompleted(this, new UrunKayitDuzenleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("GuvenlikValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UrunKayitSil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public OutputType UrunKayitSil(string UrunKimlik) {
            object[] results = this.Invoke("UrunKayitSil", new object[] {
                        UrunKimlik});
            return ((OutputType)(results[0]));
        }
        
        /// <remarks/>
        public void UrunKayitSilAsync(string UrunKimlik) {
            this.UrunKayitSilAsync(UrunKimlik, null);
        }
        
        /// <remarks/>
        public void UrunKayitSilAsync(string UrunKimlik, object userState) {
            if ((this.UrunKayitSilOperationCompleted == null)) {
                this.UrunKayitSilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUrunKayitSilOperationCompleted);
            }
            this.InvokeAsync("UrunKayitSil", new object[] {
                        UrunKimlik}, this.UrunKayitSilOperationCompleted, userState);
        }
        
        private void OnUrunKayitSilOperationCompleted(object arg) {
            if ((this.UrunKayitSilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UrunKayitSilCompleted(this, new UrunKayitSilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UrunTumListe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Urun[] UrunTumListe() {
            object[] results = this.Invoke("UrunTumListe", new object[0]);
            return ((Urun[])(results[0]));
        }
        
        /// <remarks/>
        public void UrunTumListeAsync() {
            this.UrunTumListeAsync(null);
        }
        
        /// <remarks/>
        public void UrunTumListeAsync(object userState) {
            if ((this.UrunTumListeOperationCompleted == null)) {
                this.UrunTumListeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUrunTumListeOperationCompleted);
            }
            this.InvokeAsync("UrunTumListe", new object[0], this.UrunTumListeOperationCompleted, userState);
        }
        
        private void OnUrunTumListeOperationCompleted(object arg) {
            if ((this.UrunTumListeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UrunTumListeCompleted(this, new UrunTumListeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UrunGetir", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Urun UrunGetir(string UrunKimlik) {
            object[] results = this.Invoke("UrunGetir", new object[] {
                        UrunKimlik});
            return ((Urun)(results[0]));
        }
        
        /// <remarks/>
        public void UrunGetirAsync(string UrunKimlik) {
            this.UrunGetirAsync(UrunKimlik, null);
        }
        
        /// <remarks/>
        public void UrunGetirAsync(string UrunKimlik, object userState) {
            if ((this.UrunGetirOperationCompleted == null)) {
                this.UrunGetirOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUrunGetirOperationCompleted);
            }
            this.InvokeAsync("UrunGetir", new object[] {
                        UrunKimlik}, this.UrunGetirOperationCompleted, userState);
        }
        
        private void OnUrunGetirOperationCompleted(object arg) {
            if ((this.UrunGetirCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UrunGetirCompleted(this, new UrunGetirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class Guvenlik : System.Web.Services.Protocols.SoapHeader {
        
        private string kullaniciAdiField;
        
        private string sifreField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string KullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        public string Sifre {
            get {
                return this.sifreField;
            }
            set {
                this.sifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Urun {
        
        private int idField;
        
        private string urunKimlikField;
        
        private string tanimField;
        
        private string aciklamaField;
        
        private int stokAdetField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string UrunKimlik {
            get {
                return this.urunKimlikField;
            }
            set {
                this.urunKimlikField = value;
            }
        }
        
        /// <remarks/>
        public string Tanim {
            get {
                return this.tanimField;
            }
            set {
                this.tanimField = value;
            }
        }
        
        /// <remarks/>
        public string Aciklama {
            get {
                return this.aciklamaField;
            }
            set {
                this.aciklamaField = value;
            }
        }
        
        /// <remarks/>
        public int StokAdet {
            get {
                return this.stokAdetField;
            }
            set {
                this.stokAdetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum OutputType {
        
        /// <remarks/>
        IslemBasarili,
        
        /// <remarks/>
        IslemBasarisiz,
        
        /// <remarks/>
        Tanimsiz,
        
        /// <remarks/>
        KayitliUrun,
        
        /// <remarks/>
        YeniUrun,
        
        /// <remarks/>
        UrunBulunamadi,
        
        /// <remarks/>
        GuvenlikHatasi,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UrunKayitDuzenleCompletedEventHandler(object sender, UrunKayitDuzenleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UrunKayitDuzenleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UrunKayitDuzenleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UrunKayitSilCompletedEventHandler(object sender, UrunKayitSilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UrunKayitSilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UrunKayitSilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OutputType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OutputType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UrunTumListeCompletedEventHandler(object sender, UrunTumListeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UrunTumListeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UrunTumListeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Urun[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Urun[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void UrunGetirCompletedEventHandler(object sender, UrunGetirCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UrunGetirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UrunGetirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Urun Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Urun)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591